window.KINTI_SURF_DEMO = {
  "schemaVersion": 1,
  "generatedAt": "2026-09-30T19:00:00Z",
  "spot": {
    "name": "Máncora",
    "breakLat": -4.106,
    "breakLon": -81.06,
    "oceanReferenceLat": -4.106,
    "oceanReferenceLon": -81.143
  },
  "source": {
    "mode": "demo",
    "wave": "Copernicus Marine (estructura)",
    "weather": "NOAA GFS (estructura)"
  },
  "hours": [
    {
      "timestamp": "2026-09-30T11:00:00Z",
      "swellHeightM": 0.55,
      "swellPeriodS": 7.5,
      "swellDirectionDeg": 280,
      "windSpeedKmh": 14,
      "windDirectionDeg": 45,
      "gustKmh": 19,
      "tideLevelNorm": 0.35,
      "tideTrend": "falling",
      "currentSpeedMs": 0.25,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T12:00:00Z",
      "swellHeightM": 0.85,
      "swellPeriodS": 10.5,
      "swellDirectionDeg": 300,
      "windSpeedKmh": 8,
      "windDirectionDeg": 90,
      "gustKmh": 13,
      "tideLevelNorm": 0.25,
      "tideTrend": "falling",
      "currentSpeedMs": 0.16,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T13:00:00Z",
      "swellHeightM": 1.05,
      "swellPeriodS": 12.0,
      "swellDirectionDeg": 310,
      "windSpeedKmh": 5,
      "windDirectionDeg": 105,
      "gustKmh": 10,
      "tideLevelNorm": 0.18,
      "tideTrend": "falling",
      "currentSpeedMs": 0.12,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T14:00:00Z",
      "swellHeightM": 1.15,
      "swellPeriodS": 12.8,
      "swellDirectionDeg": 315,
      "windSpeedKmh": 5,
      "windDirectionDeg": 112,
      "gustKmh": 10,
      "tideLevelNorm": 0.14,
      "tideTrend": "falling",
      "currentSpeedMs": 0.12,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T15:00:00Z",
      "swellHeightM": 1.15,
      "swellPeriodS": 12.5,
      "swellDirectionDeg": 317,
      "windSpeedKmh": 7,
      "windDirectionDeg": 120,
      "gustKmh": 12,
      "tideLevelNorm": 0.18,
      "tideTrend": "rising",
      "currentSpeedMs": 0.15,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T16:00:00Z",
      "swellHeightM": 1.12,
      "swellPeriodS": 12.2,
      "swellDirectionDeg": 320,
      "windSpeedKmh": 22,
      "windDirectionDeg": 245,
      "gustKmh": 27,
      "tideLevelNorm": 0.28,
      "tideTrend": "rising",
      "currentSpeedMs": 0.25,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T17:00:00Z",
      "swellHeightM": 1.1,
      "swellPeriodS": 12.0,
      "swellDirectionDeg": 320,
      "windSpeedKmh": 22,
      "windDirectionDeg": 245,
      "gustKmh": 27,
      "tideLevelNorm": 0.42,
      "tideTrend": "rising",
      "currentSpeedMs": 0.35,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T18:00:00Z",
      "swellHeightM": 1.08,
      "swellPeriodS": 11.8,
      "swellDirectionDeg": 318,
      "windSpeedKmh": 25,
      "windDirectionDeg": 260,
      "gustKmh": 30,
      "tideLevelNorm": 0.62,
      "tideTrend": "rising",
      "currentSpeedMs": 0.48,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T19:00:00Z",
      "swellHeightM": 1.05,
      "swellPeriodS": 11.5,
      "swellDirectionDeg": 316,
      "windSpeedKmh": 24,
      "windDirectionDeg": 255,
      "gustKmh": 29,
      "tideLevelNorm": 0.78,
      "tideTrend": "rising",
      "currentSpeedMs": 0.55,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T20:00:00Z",
      "swellHeightM": 1.03,
      "swellPeriodS": 11.4,
      "swellDirectionDeg": 314,
      "windSpeedKmh": 20,
      "windDirectionDeg": 230,
      "gustKmh": 25,
      "tideLevelNorm": 0.82,
      "tideTrend": "falling",
      "currentSpeedMs": 0.48,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T21:00:00Z",
      "swellHeightM": 1.02,
      "swellPeriodS": 11.4,
      "swellDirectionDeg": 312,
      "windSpeedKmh": 10,
      "windDirectionDeg": 135,
      "gustKmh": 15,
      "tideLevelNorm": 0.69,
      "tideTrend": "falling",
      "currentSpeedMs": 0.3,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T22:00:00Z",
      "swellHeightM": 1.0,
      "swellPeriodS": 11.2,
      "swellDirectionDeg": 310,
      "windSpeedKmh": 7,
      "windDirectionDeg": 120,
      "gustKmh": 12,
      "tideLevelNorm": 0.52,
      "tideTrend": "falling",
      "currentSpeedMs": 0.22,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    },
    {
      "timestamp": "2026-09-30T23:00:00Z",
      "swellHeightM": 0.98,
      "swellPeriodS": 11.0,
      "swellDirectionDeg": 308,
      "windSpeedKmh": 6,
      "windDirectionDeg": 115,
      "gustKmh": 11,
      "tideLevelNorm": 0.37,
      "tideTrend": "falling",
      "currentSpeedMs": 0.18,
      "currentDirectionDeg": 335,
      "waveDataAgeHours": 3,
      "weatherDataAgeHours": 1
    }
  ]
};
